_wandb:
    value:
        cli_version: 0.24.0
        e:
            omznfc024phrzdj50ivm3uusfuydwch8:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M5
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: src/xray_image_classifier/train_hydra.py
                codePathLocal: src/xray_image_classifier/train_hydra.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494332366848"
                        used: "203949821952"
                email: ritammoreiradasilva@gmail.com
                executable: /Users/rita/Documents/MLOPs/MLOps_88/.venv/bin/python3
                git:
                    commit: 5c4b8c069d7fc66cfac1d9a00ac797dbb21e278c
                    remote: https://github.com/SamuelTavares8/MLOps_88.git
                host: MacBook-Pro-de-Rita.local
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/rita/Documents/MLOPs/MLOps_88/src/xray_image_classifier/train_hydra.py
                python: CPython 3.13.11
                root: /Users/rita/Documents/MLOPs/MLOps_88
                startedAt: "2026-01-23T15:51:22.226431Z"
                writerId: omznfc024phrzdj50ivm3uusfuydwch8
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
                - 48
                - 50
                - 105
            "2":
                - 1
                - 41
                - 48
                - 50
                - 105
            "3":
                - 13
                - 16
            "4": 3.13.11
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
backbone:
    value: densenet121
batch_size:
    value: 16
device:
    value: mps
epochs_phase1:
    value: 5
epochs_phase2:
    value: 5
in_channels:
    value: 3
num_classes:
    value: 4
pretrained:
    value: true
profile:
    value: false
seed:
    value: 42
